cmake_minimum_required (VERSION 4.0)

foreach (required_variable IN ITEMS
    HDF5_PLATFORM_TEST_MODULE
    HDF5_PLATFORM_TEST_SYSTEM
    HDF5_PLATFORM_TEST_PROCESSOR
    HDF5_PLATFORM_TEST_GENERATOR
    HDF5_PLATFORM_TEST_GENERATOR_PLATFORM
    HDF5_PLATFORM_TEST_LANGUAGE
    HDF5_PLATFORM_TEST_COMPILER_ID
)
  if (NOT DEFINED ${required_variable})
    message (FATAL_ERROR "Missing required test variable: ${required_variable}")
  endif ()
endforeach ()

set (CMAKE_SYSTEM_NAME "${HDF5_PLATFORM_TEST_SYSTEM}")
set (CMAKE_SYSTEM_PROCESSOR "${HDF5_PLATFORM_TEST_PROCESSOR}")
set (CMAKE_GENERATOR "${HDF5_PLATFORM_TEST_GENERATOR}")
set (CMAKE_GENERATOR_PLATFORM "${HDF5_PLATFORM_TEST_GENERATOR_PLATFORM}")
set (CMAKE_${HDF5_PLATFORM_TEST_LANGUAGE}_COMPILER_ID "${HDF5_PLATFORM_TEST_COMPILER_ID}")

include ("${HDF5_PLATFORM_TEST_MODULE}")
hdf5_validate_platform_support (LANGUAGES "${HDF5_PLATFORM_TEST_LANGUAGE}")
