name: hdf5 dev CTest analysis runs

# Triggers the workflow on a call from another workflow
on:
  workflow_call:
    inputs:
      snap_name:
        description: 'The name in the source tarballs'
        type: string
        required: false
        default: hdfsrc
      file_base:
        description: "The common base name of the source tarballs"
        required: true
        type: string
      use_environ:
        description: 'Environment to locate files'
        type: string
        required: true
        default: snapshots

permissions:
  contents: read

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  coverage_test_linux_GCC:
  # Linux (Ubuntu) w/ gcc + coverage
  #
    name: "Ubuntu GCC Coverage"
    runs-on: ubuntu-latest
    steps:
    - name: Get Actions
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        sparse-checkout: .github/actions

    - name: Setup Doxygen
      uses: ./.github/actions/setup-doxygen

    - name: Install Dependencies (Linux_coverage)
      run: |
        sudo apt update
        sudo apt-get install ninja-build graphviz curl build-essential
        sudo apt install libssl3 libssl-dev libcurl4 libcurl4-openssl-dev
        sudo apt-get install lcov -q -y

    - name: Set file base name (Linux_coverage)
      id: set-file-base
      run: |
        FILE_NAME_BASE=$(echo "${{ inputs.file_base }}")
        echo "FILE_BASE=$FILE_NAME_BASE" >> $GITHUB_OUTPUT
        if [[ '${{ inputs.use_environ }}' == 'release' ]]
        then
          SOURCE_NAME_BASE=$(echo "${{ inputs.snap_name }}")
        else
          SOURCE_NAME_BASE=$(echo "hdfsrc")
        fi
        echo "SOURCE_BASE=$SOURCE_NAME_BASE" >> $GITHUB_OUTPUT

    # Get files created by release script
    - name: Get tgz-tarball (Linux_coverage)
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: tgz-tarball
        path: ${{ github.workspace }}

    - name: List files for the space (Linux_coverage)
      run: |
        ls -l ${{ github.workspace }}
        ls ${{ runner.workspace }}

    - name: Uncompress source (Linux_coverage)
      run: tar -zxvf ${{ github.workspace }}/${{ steps.set-file-base.outputs.FILE_BASE }}.tar.gz

    - name: Symlink script files for the space (Linux_coverage)
      uses: ./.github/actions/symlink-ctest-scripts
      with:
        source-base: ${{ steps.set-file-base.outputs.SOURCE_BASE }}

    - name: List files for the hdf5 (Linux_coverage)
      run: |
        ls ${{ runner.workspace }}/hdf5

    - name: Create options file (Linux_coverage)
      uses: "DamianReeves/write-file-action@d4ee8a06aec5db0c57a036b86f2f428e1f8b00e7" # master
      with:
        path: ${{ runner.workspace }}/hdf5/HDF5options.cmake
        write-mode: overwrite
        contents: |
            set (CTEST_DROP_SITE_INIT "my.cdash.org")
            # Change following line to submit to your CDash dashboard to a different CDash project
            set (SITE_BUILDNAME_SUFFIX "${{ steps.set-file-base.outputs.FILE_BASE }}")
            #set (CTEST_DROP_LOCATION_INIT "/submit.php?project=HDF5")
            set (LOCAL_COVERAGE_TEST "TRUE")
            set (LOCAL_USE_GCOV "TRUE")
            set (ADD_BUILD_OPTIONS "${ADD_BUILD_OPTIONS} --log-level=VERBOSE")
            set (ADD_BUILD_OPTIONS "${ADD_BUILD_OPTIONS} -DBUILD_SHARED_LIBS:BOOL=OFF")
            set (ADD_BUILD_OPTIONS "${ADD_BUILD_OPTIONS} -DBUILD_STATIC_LIBS:BOOL=ON")
            set (ADD_BUILD_OPTIONS "${ADD_BUILD_OPTIONS} -DHDF5_BUILD_CPP_LIB:BOOL=ON")
            set (ADD_BUILD_OPTIONS "${ADD_BUILD_OPTIONS} -DHDF5_ENABLE_COVERAGE:BOOL=ON")
            set (ADD_BUILD_OPTIONS "${ADD_BUILD_OPTIONS} -DCODE_COVERAGE:BOOL=ON")
            set (ADD_BUILD_OPTIONS "${ADD_BUILD_OPTIONS} -DHDF5_ENABLE_ZLIB_SUPPORT:BOOL=ON")
            set (ADD_BUILD_OPTIONS "${ADD_BUILD_OPTIONS} -DHDF5_ENABLE_SZIP_SUPPORT:BOOL=ON")
            set (ADD_BUILD_OPTIONS "${ADD_BUILD_OPTIONS} -DHDF5_ENABLE_PLUGIN_SUPPORT:BOOL=OFF")
            set (ADD_BUILD_OPTIONS "${ADD_BUILD_OPTIONS} -DLIBAEC_USE_LOCALCONTENT:BOOL=OFF")
            set (ADD_BUILD_OPTIONS "${ADD_BUILD_OPTIONS} -DZLIB_USE_LOCALCONTENT:BOOL=OFF")
            set (ADD_BUILD_OPTIONS "${ADD_BUILD_OPTIONS} -DHDF5_PACK_EXAMPLES:BOOL=OFF")
            set (ADD_BUILD_OPTIONS "${ADD_BUILD_OPTIONS} -DHDF5_PACKAGE_EXTLIBS:BOOL=OFF")
            set (ADD_BUILD_OPTIONS "${ADD_BUILD_OPTIONS} -DHDF5_NO_PACKAGES:BOOL=ON")

    - name: Run CTest (Linux_coverage)
      run: |
        cd "${{ runner.workspace }}/hdf5"
        ctest -S HDF5config.cmake,CTEST_SITE_EXT=${{ github.event.repository.full_name }}_COV,LOCAL_SUBMIT=ON,NINJA=TRUE,BUILD_GENERATOR=Unix,CTEST_SOURCE_NAME=${{ steps.set-file-base.outputs.SOURCE_BASE }} -C Debug -O hdf5.log
      shell: bash
      continue-on-error: true

    # Save log files created by CTest script
    - name: Save log (Linux_coverage)
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v5
      with:
        name: gcc-coverage-log
        path: ${{ runner.workspace }}/hdf5/hdf5.log
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
